aidants_connect_carto/apps/api/urls.py
from django.urls import path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

# from rest_framework.urlpatterns import format_suffix_patterns

from aidants_connect_carto.apps.api import views


schema_view = get_schema_view(
    openapi.Info(
        title="Aidants Connect Carto API",
        default_version="v1",
        description="description",
    ),
)

app_name = "api"
urlpatterns = [
    path("", views.api_root, name="root"),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("data-sources/", views.DataSourceList.as_view(), name="data-source-list"),
    path(
        "data-sources/<int:data_source_id>/",
        views.DataSourceDetail.as_view(),
        name="data-source-detail",
    ),
    path(
        "data-sources/<int:data_source_id>/data-sets/",
        views.DataSourceDataSetList.as_view(),
        name="data-source-data-set-list",
    ),
    path(
        "data-sources/<int:data_source_id>/data-sets/<int:data_set_id>/",
        views.DataSourceDataSetDetail.as_view(),
        name="data-source-data-set-detail",
    ),
    path("places/", views.PlaceList.as_view(), name="place-list"),
    path("places/<int:place_id>/", views.PlaceDetail.as_view(), name="place-detail"),
    path(
        "places/<int:place_id>/services/",
        views.PlaceServiceList.as_view(),
        name="place-service-list",
    ),
    path(
        "places/<int:place_id>/services/<int:service_id>/",
        views.PlaceServiceDetail.as_view(),
        name="place-service-detail",
    ),
    path("stats", views.stats, name="stats"),
    path("address/search", views.address_search, name="address-search"),
]

# urlpatterns = format_suffix_patterns(urlpatterns, allowed=["json", "html"])

aidants_connect_carto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("aidants_connect_carto.apps.api.urls")),
    path("", include("aidants_connect_carto.apps.web.urls")),
]

aidants_connect_carto/apps/web/templates/layouts/footer.html
{% load static %}

<footer class="footer" role="contentinfo">
  <div class="container">
    <div class="footer__logo">
      <a href="https://societenumerique.gouv.fr/">
        <img src="{% static 'img/logo-msn2.png' %}" alt="Logo Mission Société Numérique" />
      </a>
      <a href="https://beta.gouv.fr/">
        <img class="logo__beta" src="{% static 'img/betagouvfr.svg' %}" alt="Logo beta.gouv.fr" />
      </a>
      <ul class="footer__social">
        <li><a href="https://twitter.com/betagouv" title="Twitter"><svg class="icon icon-twitter"><use xlink:href="#twitter"></use></svg></a></li>
        <li><a href="https://github.com/betagouv/Aidants_Connect_Carto" title="Github"><svg class="icon icon-github"><use xlink:href="#github"></use></svg></a></li>
      </ul>
    </div>
    <ul class="footer__links">
      <li><h2 class="brand"><a href="https://aidantsconnect.beta.gouv.fr/">aidantsconnect.beta.gouv.fr</a></h2></li>
      <li><a href="https://beta.gouv.fr/startups/aidantsconnect">Une startup d’État de beta.gouv.fr</a></li>
      <li><a href="https://www.numerique.gouv.fr/">DINUM</a></li>
    </ul>
    <ul class="footer__links">
      <li><a href="{% url 'stats-page' %}">Statistiques</a></li>
      <li><a href="{% url 'api:schema-swagger-ui' %}">API</a></li>
    </ul>
  </div>
</footer>

aidants_connect_carto/apps/web/templates/layouts/main.html
{% load static %}
<!doctype html>
<html itemscope itemtype="http://schema.org/WebPage" lang="fr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Aidants Connect Carto</title>

  <link href="{% static 'css/template.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">

  <!-- Extra styles -->
  {% block extracss %}
  {% endblock extracss %}

</head>

<body>
  <svg aria-hidden="true" focusable="false" style="display:none">
    <defs>
      <symbol viewBox="0 0 32 32" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414" id="copy" xmlns="http://www.w3.org/2000/svg"><path d="M19.75 8.5V1H6.625L1 6.625V23.5h11.25V31H31V8.5H19.75zM6.625 3.651v2.974H3.651l2.974-2.974zm-3.75 17.974V8.5H8.5V2.875h9.375V8.5l-5.625 5.625v7.5H2.875zm15-10.474v2.974h-2.974l2.974-2.974zm11.25 17.974h-15V16h5.625v-5.625h9.375v18.75z" fill-rule="nonzero"/></symbol>
      <symbol viewBox="0 0 32 32" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414" id="envelope" xmlns="http://www.w3.org/2000/svg"><g fill-rule="nonzero"><path d="M30.1 5.419c-9.355-.002-18.733-.005-28.1-.005A1.06 1.06 0 0 0 .975 6.439v19.122A1.06 1.06 0 0 0 2 26.586h28a1.061 1.061 0 0 0 1.025-1.025V6.439a1.056 1.056 0 0 0-.925-1.02zM3.025 7.464h25.95v17.072H3.025V7.464z"/><path d="M30.06 9.513c.933.098 1.382 1.395.393 1.945L16.54 18.287c-.438.188-.479.178-.893 0L1.733 11.458c-1.743-.968-.065-2.254.894-1.842l13.466 6.61 13.562-6.651c.3-.094.312-.062.405-.062z"/></g></symbol>
      <symbol viewBox="0 0 32 32" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414" id="github" xmlns="http://www.w3.org/2000/svg"><path d="M16 1.371c-8.284 0-15 6.715-15 15 0 6.627 4.298 12.25 10.258 14.233.75.138 1.026-.326 1.026-.722 0-.357-.014-1.54-.021-2.793-4.174.907-5.054-1.77-5.054-1.77-.682-1.733-1.665-2.195-1.665-2.195-1.361-.931.103-.912.103-.912 1.506.106 2.299 1.546 2.299 1.546 1.338 2.293 3.509 1.63 4.365 1.247.134-.969.523-1.631.952-2.006-3.331-.379-6.834-1.666-6.834-7.413 0-1.638.586-2.976 1.546-4.027-.156-.378-.669-1.903.145-3.969 0 0 1.26-.403 4.126 1.537a14.453 14.453 0 0 1 3.755-.505c1.274.006 2.558.173 3.757.505 2.864-1.94 4.121-1.537 4.121-1.537.816 2.066.303 3.591.147 3.969.962 1.05 1.544 2.389 1.544 4.027 0 5.761-3.509 7.029-6.849 7.401.538.466 1.017 1.379 1.017 2.778 0 2.007-.018 3.623-.018 4.117 0 .399.27.867 1.03.72C26.707 28.616 31 22.996 31 16.371c0-8.285-6.716-15-15-15z" fill-rule="nonzero"/></symbol>
      <symbol viewBox="0 0 32 32" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414" id="twitter" xmlns="http://www.w3.org/2000/svg"><path d="M31.003 6.695c-1.102.492-2.291.82-3.533.966a6.185 6.185 0 0 0 2.706-3.404 12.404 12.404 0 0 1-3.908 1.495 6.154 6.154 0 0 0-4.495-1.94 6.153 6.153 0 0 0-5.994 7.553A17.468 17.468 0 0 1 3.093 4.932a6.15 6.15 0 0 0-.831 3.094 6.147 6.147 0 0 0 2.736 5.122 6.16 6.16 0 0 1-2.789-.768v.076a6.154 6.154 0 0 0 4.94 6.034 6.149 6.149 0 0 1-2.783.106 6.177 6.177 0 0 0 5.748 4.277 12.347 12.347 0 0 1-9.117 2.549 17.4 17.4 0 0 0 9.44 2.766c11.32 0 17.513-9.381 17.513-17.514 0-.269-.005-.533-.017-.796a12.405 12.405 0 0 0 3.07-3.182v-.001z" fill-rule="nonzero"/></symbol>
    </defs>
  </svg>
  {% block nav %}
    {% include 'layouts/nav.html' %}
  {% endblock nav %}

  {% block hero %}
  {% endblock hero %}

  <main>
    {% block content %}
    {% endblock content %}
  </main>

  {% block footer %}
    {% include 'layouts/footer.html' %}
  {% endblock footer %}

  {% block extrajs %}
  {% endblock extrajs %}
</body>

</html>

aidants_connect_carto/apps/web/templates/layouts/nav.html
{% load static %}

<header class="navbar">
  <div class="navbar__container">
    <a class="navbar__home" href="{% url 'home-page' %}">
      <img class="navbar__logo" src="{% static 'img/logo-marianne.svg' %}" alt="Logo République Française Marianne" />
      <img src="{% static 'img/aidants-connect_logo.png' %}" class="navbar__gouvfr" alt="Logo Aidants Connect" />
      <h2>&nbsp;Carto</h2>
    </a>
    <nav role="navigation">
      <ul class="nav__links">
        <li class="nav__item">
          <a href="{% url 'places-list' %}"  {% if request.path == '/lieux' %}class="active"{% endif %}>
            🔍&nbsp;Rechercher un lieu
          </a>
        </li>
        <li class="nav__item">
          <a href="{% url 'data-sources-list' %}"  {% if request.path == '/datasets' %}class="active"{% endif %}>
            Jeux de données
          </a>
        </li>
        <!-- <li class="nav__item">
          <a href="{% url 'place-create' %}"  {% if '/nouveau-lieu' in request.path %}class="active"{% endif %}>
            Ajouter un lieu
          </a>
        </li> -->
      </ul>
    </nav>
  </div>
  <div class="notification full-width" role="alert">
    Vous êtes sur un site en construction, l’interface proposée sera amenée à changer grâce à vos <a href="https://github.com/betagouv/Aidants_Connect_Carto/issues/new">retours</a> !
  </div>
</header>