aidants_connect_carto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("aidants_connect_carto.apps.api.urls")),
    path("", include("aidants_connect_carto.apps.web.urls")),
]

aidants_connect_carto_api/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField
from django.core.validators import RegexValidator

import humanized_opening_hours as hoh

from aidants_connect_carto_api import constants


class Place(models.Model):
    AUTO_POPULATED_FIELDS = [
        "address_housenumber",
        "address_street",
        "address_postcode",
        "address_citycode",
        "address_city",
        "address_departement_code",
        "address_departement_name",
        "address_region_name",
        "latitude",
        "longitude",
        "osm_node_id",
    ]

    # --- basics
    name = models.CharField(
        verbose_name="Le nom du lieu", max_length=300, help_text="BetaGouv"
    )
    supporting_structure_name = models.CharField(
        verbose_name="Le nom de la structure porteuse du lieu",
        blank=True,
        max_length=300,
        help_text="Services du Premier Ministre",
    )
    description = models.TextField(
        verbose_name="Une description du lieu",
        blank=True,
        help_text="L'incubateur de Services Numériques de l'État",
    )
    type = models.CharField(
        verbose_name="La typologie du lieu",
        max_length=32,
        choices=constants.PLACE_TYPE_CHOICES,
        default=constants.CHOICE_OTHER,
        help_text="Administration",
    )  # ArrayField (multiple choices) ?
    status = models.CharField(
        verbose_name="Le statut du lieu",
        max_length=32,
        choices=constants.PLACE_STATUS_CHOICES,
        default=constants.CHOICE_OTHER,
        help_text="Public",
    )
    legal_entity_type = models.CharField(
        verbose_name="La nature juridique du lieu",
        max_length=32,
        choices=constants.PLACE_LEGAL_ENTITY_TYPE_CHOICES,
        default=constants.CHOICE_OTHER,
        help_text="",
    )

    # --- location
    address_raw = models.CharField(
        verbose_name="L'adresse complète",
        max_length=300,
        help_text="20 Avenue de Ségur 75007 Paris",
    )
    address_housenumber = models.CharField(
        verbose_name="Le numéro avec indice de répétition éventuel (bis, ter, A, B)",
        max_length=5,
        blank=True,
        help_text="20",
    )
    address_street = models.CharField(
        verbose_name="Le nom de la rue",
        max_length=150,
        blank=True,
        help_text="Avenue de Ségur",
    )
    address_postcode = models.CharField(
        verbose_name="Le code postal", max_length=5, blank=True, help_text="75007"
    )
    address_citycode = models.CharField(
        verbose_name="Le code INSEE de la commune",
        max_length=5,
        blank=True,
        help_text="75107",
    )
    address_city = models.CharField(
        verbose_name="Le nom de la commune",
        max_length=150,
        blank=True,
        help_text="Paris",
    )
    address_departement_code = models.CharField(
        verbose_name="Le numéro de département",
        max_length=3,
        blank=True,
        help_text="75",
    )
    address_departement_name = models.CharField(
        verbose_name="Le nom du département",
        max_length=150,
        blank=True,
        help_text="Paris",
    )
    address_region_name = models.CharField(
        verbose_name="Le nom de la région",
        max_length=150,
        blank=True,
        help_text="Île-de-France",
    )
    latitude = models.FloatField(
        verbose_name="La latitude (coordonnée géographique)",
        blank=True,
        null=True,
        help_text="48.850699",
    )
    longitude = models.FloatField(
        verbose_name="La longitude (coordonnée géographique)",
        blank=True,
        null=True,
        help_text="2.308628",
    )
    is_itinerant = models.BooleanField(
        verbose_name="Le lieu est-il itinérant ?", default=False
    )
    itinerant_details = models.TextField(
        verbose_name="Le details des déplacements", blank=True
    )
    is_online = models.BooleanField(
        verbose_name="Le lieu est-il uniquement en ligne ?", default=False
    )

    # --- contact
    contact_phone_raw = models.CharField(
        verbose_name="Le numéro de téléphone brut", max_length=300
    )
    phone_regex = RegexValidator(
        regex=r"^[0-9]{10}$",
        message="le numéro de téléphone doit être au format 0123456789",
    )
    contact_phone = models.CharField(
        verbose_name="Le numéro de téléphone",
        max_length=10,
        blank=True,
        null=True,
        validators=[phone_regex],
        help_text="0123456789",
    )
    # contact_phone_international = models.CharField(help_text="") # regex="^[0-9]+$"
    contact_email = models.EmailField(
        verbose_name="Le courriel",
        max_length=150,
        blank=True,
        help_text="exemple@email.fr",
    )
    contact_website = models.URLField(
        verbose_name="L'adresse du site internet",
        max_length=300,
        blank=True,
        help_text="https://beta.gouv.fr/",
    )
    contact_facebook = models.URLField(
        verbose_name="L'adresse de la page Facebook", max_length=300, blank=True
    )
    contact_twitter = models.URLField(
        verbose_name="L'adresse de la page Twitter",
        max_length=300,
        blank=True,
        help_text="https://twitter.com/betagouv",
    )
    contact_youtube = models.URLField(
        verbose_name="L'adresse de la page Youtube", max_length=300, blank=True
    )

    # --- opening hours
    opening_hours_raw = models.TextField(
        verbose_name="Les horaires d'ouverture",
        blank=True,
        help_text="Du lundi au vendredi de 8h à 20h",
    )
    opening_hours_osm_format = models.CharField(
        verbose_name="Les horaires d'ouverture au format OpenStreetMap",
        max_length=150,
        blank=True,
        help_text="Mo-Fr 8:00-20:00",
    )

    # --- equipments
    # equipments = ArrayField() # EQUIPMENT_CHOICES
    has_equipment_wifi = models.BooleanField(verbose_name="WiFi", default=False)
    has_equipment_computer = models.BooleanField(
        verbose_name="Ordinateur", default=False
    )
    has_equipment_scanner = models.BooleanField(verbose_name="Scanner", default=False)
    has_equipment_printer = models.BooleanField(
        verbose_name="Imprimante", default=False
    )
    equipment_other = models.CharField(
        verbose_name="Autres équipements disponibles", max_length=300, blank=True
    )

    # --- accessibility
    # accessibility = ArrayField(
    #     verbose_name="Accessible aux formes de handicap suivantes",
    #     base_field=models.CharField(
    #         max_length=32,
    #         blank=True,
    #         choices=HANDICAP_CHOICES
    #     ),
    #     default=list,
    #     blank=True
    # )
    has_accessibility_hi = models.BooleanField(
        verbose_name="Handicap auditif", default=False
    )
    # has_accessibility_mei = models.BooleanField(
    #     verbose_name="Handicap mental", default=False
    # )
    has_accessibility_mi = models.BooleanField(
        verbose_name="Handicap moteur", default=False
    )
    has_accessibility_pi = models.BooleanField(
        verbose_name="Handicap intellectuel ou psychique", default=False
    )
    has_accessibility_vi = models.BooleanField(
        verbose_name="Handicap visuel", default=False
    )

    # --- languages
    # languages = ArrayField(
    #     verbose_name="Langues parlées",
    #     base_field=models.CharField(
    #         max_length=32,
    #         blank=True,
    #         choices=LANGUAGE_CHOICES
    #     ),
    #     default=list,
    #     blank=True
    # )
    languages = models.CharField(
        verbose_name="Langues parlées",
        max_length=150,
        blank=True,
        help_text="Français, Anglais, ...",
    )

    # --- support
    target_audience_raw = models.CharField(
        verbose_name="Le public cible", max_length=150, blank=True
    )
    target_audience = ArrayField(
        verbose_name="Public cible",
        base_field=models.CharField(
            max_length=32, blank=True, choices=constants.TARGET_AUDIENCE_CHOICES
        ),
        default=list,
        blank=True,
    )

    # --- payment
    payment_methods = models.CharField(
        verbose_name="Les moyens de paiement",
        max_length=150,
        blank=True,
        help_text="Espèces, Carte Bancaire, ...",
    )  # PAYMENT_CHOICES

    # --- other
    additional_information = JSONField(
        verbose_name="Informations additionnelles stockées au format JSON",
        blank=True,
        null=True,
    )

    # --- links to other databases
    osm_node_id = models.IntegerField(
        verbose_name="OpenStreetMap node id",
        blank=True,
        null=True,
        help_text="5266052428",
    )

    # --- timestamps
    created_at = models.DateTimeField(
        verbose_name="La date de création", auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="La date de dernière modification", auto_now=True
    )

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.name}"

    @property
    def service_count(self) -> int:
        return self.services.count()

    @property
    def service_list(self) -> list():
        return self.services.values_list("name", flat=True)

    @property
    def opening_hours_description(self) -> list:
        """
        Transform opening_hours_osm_format into a readable description
        'Mo-Fr 8:00-20:00' --> ['Du lundi au vendredi : 08:00 – 20:00.']

        TODO: Store as model field ?
        """
        if not self.opening_hours_osm_format:
            return []

        oh = hoh.OHParser(self.opening_hours_osm_format, locale="fr")
        return oh.description()

    @property
    def opening_hours_week_description(self) -> list:
        """
        Transform `opening_hours_osm_format` into a list
        of readable descriptions per day.

        For example, if `opening_hours_osm_format` contains the string

aidants_connect_carto/apps/web/templates/places/place_create.html
{% extends 'layouts/main.html' %}

{% load static %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'css/libraries/jquery-typeahead.2.11.0.min.css' %}">

<link rel="stylesheet" href="{% static 'css/libraries/leaflet@1.6.0.css' %}">

<link rel="stylesheet" href="{% static 'css/libraries/fullcalendar.core@4.4.0.main.min.css' %}">
<link rel="stylesheet" href="{% static 'css/libraries/fullcalendar.daygrid@4.4.0.main.min.css' %}">
<link rel="stylesheet" href="{% static 'css/libraries/fullcalendar.timegrid@4.4.0.main.min.css' %}">
<link rel="stylesheet" href="{% static 'css/libraries/yohours.css' %}">
{% endblock extracss %}

{% block content %}
<section class="section section-white">
  <div class="container">
    <h1>Formulaire pour {% if action == 'create' %}ajouter{% else %}modifier{% endif %} un lieu</h1>
  </div>
</section>
<section class="section section-grey">
  <div class="container">
    {% if action == 'create' %}
      <form action="{% url 'place-create' %}" method="POST">
    {% else %}
      <form action="{% url 'place-update' place_id=place_id %}" method="POST">
    {% endif %}

      {% csrf_token %}

      {% if form.errors %}
        <div class="notification error" role="alert">{{ form.errors }}</div>
      {% endif %}

      <h3>Les infos de base</h3>

      <div class="form__group">
        <label class="{% if form.name.field.required %}required{% endif %}" for="{{ form.name.id_for_label }}">{{ form.name.label | safe }}&nbsp;:</label>
        {{ form.name }}
      </div>
      <div class="form__group">
        <label class="{% if form.address_raw.field.required %}required{% endif %}" for="{{ form.address_raw.id_for_label }}">{{ form.address_raw.label | safe }}&nbsp;:</label>
        <!-- {{ form.address_raw }} -->
        <div class="typeahead__container">
          <div class="typeahead__field">
            <div class="typeahead__query">
              <input type="text" id="id_address_raw" class="js-typeahead" name="address_raw" maxlength="300" autocomplete="off">
            </div>
            <div class="typeahead__button" title="Réinitialiser">
              <button>
                <!-- <span class="typeahead__cancel-icon"></span> -->
                <span>X</span>
              </button>
            </div>
          </div>
        </div>

        <label><i>Champs remplis automatiquement grâce à <a href="https://adresse.data.gouv.fr/" target="_blank">https://adresse.data.gouv.fr/</a></i></label>
        <div class="row">
          <div class="col-50">
            <div class="input__group">
              {{ form.address_housenumber }}
            </div>
            <div class="input__group">
              {{ form.address_street }}
            </div>
            <div class="input__group">
              {{ form.address_postcode }}
              {{ form.address_citycode }}
            </div>
            <div class="input__group">
              {{ form.address_city }}
            </div>
            <div class="input__group">
              {{ form.address_departement_code }}
              {{ form.address_departement_name }}
              {{ form.address_region_code }}
            </div>
            <br />
            <div class="input__group">
              {{ form.latitude }}
            </div>
            <div class="input__group">
              {{ form.longitude }}
            </div>
          </div>
          <div class="col-50 no-margin">
            <div id="map-place-form"></div>
          </div>
        </div>
      </div>
      <div class="form__group">
        <label>{{ form.is_itinerant.label | safe }}</label>
        <div class="input__group">
          {{ form.is_itinerant }}
          <label class="label-inline" for="{{ form.is_itinerant.id_for_label }}">Itinérant</label>
        </div>
      </div>
      <div id="itinerant_details_form_group" class="form__group" style="display: {{ form.is_itinerant | yesno:'none,block' }}">
        <label for="{{ form.itinerant_details.id_for_label }}">{{ form.itinerant_details.label | safe }}&nbsp;:</label>
        {{ form.itinerant_details }}
      </div>

      <h3>Contact</h3>

      <div class="form__group">
        <label for="{{ form.contact_email.id_for_label }}">{{ form.contact_email.label | safe }}&nbsp;:</label>
        {{ form.contact_email }}
      </div>
      <div class="form__group">
        <label for="{{ form.contact_phone.id_for_label }}">{{ form.contact_phone.label | safe }}&nbsp;:</label>
        {{ form.contact_phone }}
      </div>
      <div class="form__group">
        <label for="{{ form.contact_website_url.id_for_label }}">{{ form.contact_website_url.label | safe }}&nbsp;:</label>
        {{ form.contact_website_url }}
      </div>

      <h3>Service(s) disponible(s)</h3>

      <p>Voir plus loin</p>

      <h3>Equipement(s) disponible(s)</h3>

      <div class="form__group">
        <label>Le lieu a-t-il les équipements suivants ?</label>
        <div class="input__group">
          {{ form.has_equipment_wifi }}
          <label class="label-inline" for="{{ form.has_equipment_wifi.id_for_label }}">{{ form.has_equipment_wifi.label | safe }}</label>
        </div>
        <div class="input__group">
          {{ form.has_equipment_computer }}
          <label class="label-inline" for="{{ form.has_equipment_computer.id_for_label }}">{{ form.has_equipment_computer.label | safe }}</label>
        </div>
        <div class="input__group">
          {{ form.has_equipment_scanner }}
          <label class="label-inline" for="{{ form.has_equipment_scanner.id_for_label }}">{{ form.has_equipment_scanner.label | safe }}</label>
        </div>
        <div class="input__group">
          {{ form.has_equipment_printer }}
          <label class="label-inline" for="{{ form.has_equipment_printer.id_for_label }}">{{ form.has_equipment_printer.label | safe }}</label>
        </div>
      </div>
      <div class="form__group">
        <label for="{{ form.equipment_other.id_for_label }}">{{ form.equipment_other.label | safe }}&nbsp;:</label>
        {{ form.equipment_other }}
      </div>

      <h3>L'accès</h3>

      <div class="form__group">
        <label for="{{ form.opening_hours_osm_format.id_for_label }}">{{ form.opening_hours_osm_format.label | safe }}&nbsp;:</label>
        <!-- {{ form.opening_hours_osm_format }} -->
        <input type="text" name="opening_hours_osm_format" maxlength="150" id="id_opening_hours_osm_format" class="myOpeningHours">
      </div>

      <div class="form__group">
        <label>Conditions d'accueil des personnes handicapées&nbsp;:</label>
        <div class="input__group">
          {{ form.has_accessibility_hi }}
          <label class="label-inline" for="{{ form.has_accessibility_hi.id_for_label }}">{{ form.has_accessibility_hi.label | safe }}</label>
        </div>
        <div class="input__group">
          {{ form.has_accessibility_mi }}
          <label class="label-inline" for="{{ form.has_accessibility_mi.id_for_label }}">{{ form.has_accessibility_mi.label | safe }}</label>
        </div>
        <div class="input__group">
          {{ form.has_accessibility_pi }}
          <label class="label-inline" for="{{ form.has_accessibility_pi.id_for_label }}">{{ form.has_accessibility_pi.label | safe }}</label>
        </div>
        <div class="input__group">
          {{ form.has_accessibility_vi }}
          <label class="label-inline" for="{{ form.has_accessibility_vi.id_for_label }}">{{ form.has_accessibility_vi.label | safe }}</label>
        </div>
      </div>
      <div class="form__group">
        <label for="{{ form.languages.id_for_label }}">{{ form.languages.label | safe }}&nbsp;:</label>
        {{ form.languages }}
      </div>
      <div class="form__group">
        <label for="{{ form.payment_methods.id_for_label }}">{{ form.payment_methods.label | safe }}&nbsp;:</label>
        {{ form.payment_methods }}
      </div>

      <h3>Labels</h3>

      <div class="form__group">
        <div class="input__group">
          {{ form.has_label_fs }}
          <label class="label-inline" for="{{ form.has_label_fs.id_for_label }}">{{ form.has_label_fs.label | safe }}</label>
        </div>
      </div>

      <div class="form__group">
        <input type="submit" value="Sauvegarder" disabled>
      </div>
    </form>
  </div>
</section>
{% endblock content %}

{% block extrajs %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script> -->
<script src="{% static 'js/libraries/jquery-typeahead.2.11.0.min.js' %}"></script>

<script src="{% static 'js/libraries/leaflet@1.6.0.js' %}"></script>

<script src="{% static 'js/libraries/fullcalendar.core@4.4.0.main.min.js' %}"></script>
<script src="{% static 'js/libraries/fullcalendar.daygrid@4.4.0.main.min.js' %}"></script>
<script src="{% static 'js/libraries/fullcalendar.timegrid@4.4.0.main.min.js' %}"></script>
<script src="{% static 'js/libraries/fullcalendar.interaction@4.4.0.main.min.js' %}"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/caret/1.0.0/jquery.caret.min.js" crossorigin="anonymous"></script> -->
<script src="{% static 'js/libraries/moment-with-locales.2.22.1.min.js' %}"></script>
<script src="{% static 'js/libraries/popper.1.14.3.min.js' %}"></script>
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script> -->
<script src="{% static 'js/libraries/jsmart.3.0.3.min.js' %}"></script>
<script src="{% static 'js/libraries/jed.min.js' %}"></script>
<script src="{% static 'js/libraries/yohours.i18n.en.min.js' %}"></script>
<script src="{% static 'js/libraries/yohours.js' %}"></script>
<script>
  // leaflet map
  var map = L.map('map-place-form').setView([46.7, 2.1], 5);
  var marker;
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);

  // jquery typeahead
  $.typeahead({
    input: "#id_address_raw",
    minLength: 5,
    maxItem: 10,
    order: "asc",
    dynamic: true,
    delay: 500,
    filter: false,
    backdrop: {
      "background-color": "#fff"
    },
    emptyTemplate: "Aucune adresse trouvée",
    display: "properties.label",
    source: {
      address: {
        ajax: function (query) {
          console.log(query);
          return {
            type: "GET",
            url: "{% url 'address-search' %}",
            data: {
              q: query
            },
            path: "features",
            callback: {
              done: function (data) {
                console.log(data);
                return data;
              }
            }
          }
        }
      }
    },
    callback: {
      onInit: function (node) {
        console.log(node);
      },
      onClick: function (node, a, item, event) {
        populateAddress(item);
      },
    }
  });

  $(".typeahead__button").click(function(event) {
    event.stopPropagation();
    clearAddress();
  });

  function populateAddress(item) {
    $("#id_address_housenumber").val(item.properties.housenumber);
    $("#id_address_street").val(item.properties.street);
    $("#id_address_postcode").val(item.properties.postcode);
    $("#id_address_citycode").val(item.properties.citycode);
    $("#id_address_city").val(item.properties.city);
    item_context_split = item.properties.context.split(", ");
    $("#id_address_departement_code").val(item_context_split.address_departement_code);
    $("#id_address_departement_name").val(item_context_split.address_departement_name);
    $("#id_address_region_name").val(item_context_split.address_region_name);
    $("#id_latitude").val(item.geometry.coordinates[1]);
    $("#id_longitude").val(item.geometry.coordinates[0]);
    marker = L.marker(item.geometry.coordinates.reverse()).addTo(map);
  }

  function clearAddress() {
    $("#id_address_raw").val("");
    $("#id_address_housenumber").val("");
    $("#id_address_street").val("");
    $("#id_address_postcode").val("");
    $("#id_address_citycode").val("");
    $("#id_address_city").val("");
    $("#id_address_departement_code").val("");
    $("#id_address_departement_name").val("");
    $("#id_address_region_name").val("");
    $("#id_latitude").val("");
    $("#id_longitude").val("");
    map.removeLayer(marker);
  }

  $('.myOpeningHours').yoHours({
		bootstrapVersion: 'bootstrap4', // or bootstrap4
		delay: 700, // in ms, delay before plugin starts parsing input string
		height: 500, // in pixels, max height of calendar
    locale: 'en', // must be loaded before yohours like in example above
    minimal: true,
    slotDuration: '00:15:00'
	}, {
  });
  $('#yh1_yo-hours-toggle').click(function() {
    $('#yh1_yo-hours-calendar').slideToggle();
  });

  document.querySelector("input[id=id_is_itinerant]").addEventListener('change', function() {
    document.getElementById("itinerant_details_form_group").style.display = this.checked ? "none" : "block";
  });
</script>
{% endblock extrajs %}